# Generated by Django 4.1.2 on 2022-10-06 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formapago', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='i001t_tipo_forma_pago',
            table='i001t_tipo_forma_pago',
        ),
        migrations.AlterModelTable(
            name='i002t_forma_pago',
            table='i002t_forma_pago',
        ),
    ]
