# Generated by Django 4.1.2 on 2022-10-06 17:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('formapago', '0002_alter_i001t_tipo_forma_pago_table_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='i001t_tipo_forma_pago',
            options={'ordering': ['-fe_crea'], 'verbose_name': 'Tipo Forma de Pago', 'verbose_name_plural': 'Tipo Formas de Pago'},
        ),
        migrations.AlterModelOptions(
            name='i002t_forma_pago',
            options={'ordering': ['-fe_crea'], 'verbose_name': 'Forma de Pago', 'verbose_name_plural': 'Formas de Pago'},
        ),
        migrations.AddField(
            model_name='i001t_tipo_forma_pago',
            name='fe_crea',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Seleccione fecha de creación del registro', verbose_name='fecha crea'),
        ),
        migrations.AddField(
            model_name='i001t_tipo_forma_pago',
            name='fe_modifica',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Seleccione fecha de modificación del registro', verbose_name='fecha modifica'),
        ),
        migrations.AddField(
            model_name='i001t_tipo_forma_pago',
            name='nu_orden',
            field=models.IntegerField(blank=True, default='1', help_text='Orden de presentacion de tienda en destacados', null=True, verbose_name='Orden'),
        ),
        migrations.AddField(
            model_name='i002t_forma_pago',
            name='fe_crea',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Seleccione fecha de creación del registro', verbose_name='fecha crea'),
        ),
        migrations.AddField(
            model_name='i002t_forma_pago',
            name='fe_modifica',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Seleccione fecha de modificación del registro', verbose_name='fecha modifica'),
        ),
        migrations.AddField(
            model_name='i002t_forma_pago',
            name='nu_orden',
            field=models.IntegerField(blank=True, default='1', help_text='Orden de presentacion de la forma de pago segun su uso', null=True, verbose_name='Orden'),
        ),
        migrations.AddField(
            model_name='i002t_forma_pago',
            name='tx_cedula_titular',
            field=models.CharField(default='15908576', help_text='Ingrese Cedula del titular de la cuenta bancaria', max_length=50, null=True, verbose_name='Cedula'),
        ),
        migrations.AddField(
            model_name='i002t_forma_pago',
            name='tx_codigo_banco',
            field=models.CharField(default='0000', help_text='Ingrese Codigo del Banco de la cuenta bancaria', max_length=50, null=True, verbose_name='Codigo de Banco'),
        ),
        migrations.AddField(
            model_name='i002t_forma_pago',
            name='tx_correo_titular',
            field=models.CharField(default='gamboaej@hotmail.com', help_text='Ingrese Correo del titular de la cuenta bancaria', max_length=50, null=True, verbose_name='Correo Electrónico'),
        ),
        migrations.AddField(
            model_name='i002t_forma_pago',
            name='tx_direccion_cartera',
            field=models.CharField(default='D5pb932C7ugcMkbCpgw4hQDDzB5wgKd2eg', help_text='Ingrese Cartera de criptomoneda', max_length=50, null=True, verbose_name='Direccion Cartera'),
        ),
        migrations.AddField(
            model_name='i002t_forma_pago',
            name='tx_enlace',
            field=models.SlugField(default=1, help_text='URL de la página de la forma de pago, creado a partir del nombre.', max_length=110, unique=True, verbose_name='enlace'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='i002t_forma_pago',
            name='tx_nombre',
            field=models.CharField(default='Forma de Pago', help_text='Ingrese nombre de la forma de pago', max_length=50, unique=True, verbose_name='nombre'),
        ),
        migrations.AddField(
            model_name='i002t_forma_pago',
            name='tx_nombre_titular',
            field=models.CharField(default='Elvis Gamboa', help_text='Ingrese Nombre del titular de la cuenta bancaria', max_length=50, null=True, verbose_name='Nombre'),
        ),
        migrations.AddField(
            model_name='i002t_forma_pago',
            name='tx_numero_cuenta',
            field=models.CharField(default='0000-0000-0000-0000-0000', help_text='Ingrese Numero de la cuenta bancaria', max_length=50, null=True, verbose_name='Numero Cuenta'),
        ),
        migrations.AddField(
            model_name='i002t_forma_pago',
            name='tx_observacion',
            field=models.CharField(default='Forma de Pago', help_text='Ingrese observacion relevante del registro', max_length=50, null=True, verbose_name='Observacion'),
        ),
        migrations.AddField(
            model_name='i002t_forma_pago',
            name='tx_telefono_titular',
            field=models.CharField(default='0000-0000000', help_text='Ingrese Numero de telefono del titular de la cuenta bancaria', max_length=50, null=True, verbose_name='Telefono'),
        ),
        migrations.AddField(
            model_name='i002t_forma_pago',
            name='tx_tipo_cuenta',
            field=models.CharField(default='AAAAAAA', help_text='Ingrese Tipo de Cuenta bancaria', max_length=50, null=True, verbose_name='Tipo de Cuenta'),
        ),
    ]
