# Generated by Django 4.1.2 on 2022-10-06 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formapago', '0003_alter_i001t_tipo_forma_pago_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='i002t_forma_pago',
            name='tx_foto',
            field=models.ImageField(default='formapago/fp_no_disponible.png', upload_to='formapago', verbose_name='imagen'),
        ),
    ]
